#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path_url)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path_url}"

# Restore sources & data
src_path="/var/www/${app}"
sudo cp -a ./sources "$src_path"

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root: "$src_path"

### MySQL (remove if not used) ###
# If a MySQL database is used:
# # Create and restore the database
db_name=$app
db_user=$app
db_pwd=$(ynh_app_setting_get "$app" mysqlpwd)
ynh_mysql_create_db "$db_name" "$db_user" "$db_pwd"
ynh_mysql_connect_as "$db_user" "$db_pwd" "$db_name" < ./dump.sql
### MySQL end ###

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

### PHP (remove if not used) ###
# If a dedicated php-fpm process is used:
# # Copy PHP-FPM pool configuration and reload the service
# sudo cp -a ./php-fpm.conf "/etc/php5/fpm/pool.d/${app}.conf"
# sudo service php5-fpm reload
### PHP end ###

# Restart webserver
sudo service nginx reload
